### ISSUE TITLE
Upgrade Spring Boot to the latest version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-testing-restdocs#16]
Update the guide to use the most recent Spring Boot version.

To do so, change the Spring Boot version in:

initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml

**Comment by Ubunfu** [comment]
@Buzzardo just FYI, that should do it, yea?

**Comment by Buzzardo** [comment]
Yup :)
