### ISSUE TITLE
code in project not up to date with README

### ISSUE THREAD

**Issue by fabienhinault** [spring-guides/gs-testing-restdocs#18]
https://github.com/spring-guides/gs-testing-restdocs/blob/main/complete/src/test/java/com/example/testingrestdocs/WebLayerTest.java

is not consistent with the code extract in 

https://github.com/spring-guides/gs-testing-restdocs/blob/main/README.adoc#test-the-application.

pom.xml is also different in the file README.adoc and in the source tree.

**Comment by Buzzardo** [comment]
The first problem is because we hard-coded the contents of that block rather than use a link to the file (which is the right way to do it). The second one is because we had a missing pair of tags in the complete/pom.xml file. I'll push a fix momentarily.

**Comment by Buzzardo** [comment]
Fixed in https://github.com/spring-guides/gs-testing-restdocs/commit/875af90b61298126111f62f8a2e6c064e447f501

**Comment by Buzzardo** [comment]
Thanks for catching those issues.
